{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shinel.fullname" . }}-redis
  labels:
    {{- include "shinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "shinel.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "shinel.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.redis.repository }}:{{ .Values.image.redis.tag | default "7-alpine" }}"
          imagePullPolicy: {{ .Values.image.redis.pullPolicy | default "IfNotPresent" }}
          command: ["sh", "-c", "exec redis-server --requirepass \"$REDIS_PASSWORD\""]
          ports:
            - name: redis
              containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "shinel.fullname" . }}
                  key: redis-password
            - name: REDISCLI_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ include "shinel.fullname" . }}
                  key: redis-password
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            periodSeconds: 20
{{- end }}
